import tvm
import tvm.s_tir
from tvm import relax
from tvm.script import ir as I
from tvm.script import relax as R
from tvm.script import tirx as T

# ==============================================================================
# 1. Prerequisite: Rebuild the Fused Module (Step 4A)
# ==============================================================================
@I.ir_module
class ConvAddModule:
    @R.function
    def main(data: R.Tensor((1, 3, 224, 224), dtype="float32"),
             weight: R.Tensor((16, 3, 3, 3), dtype="float32"),
             bias: R.Tensor((16, 1, 1), dtype="float32")):
        with R.dataflow():
            conv = R.nn.conv2d(data, weight, padding=(1, 1), data_layout="NCHW", kernel_layout="OIHW")
            out = R.add(conv, bias)
            relu = R.nn.relu(out)
            R.output(relu)
        return relu

# Run Graph-Level Passes to get the Fused TIR
mod = relax.transform.LegalizeOps()(ConvAddModule)
mod = relax.transform.AnnotateTIROpPattern()(mod)
mod = relax.transform.FuseOps()(mod)
mod = relax.transform.FuseTIR()(mod)

print("--- 1. Before Tiling (Output of FuseTIR) ---")
mod.show()

# ==============================================================================
# 2. TensorIR Tiling & Scheduling (Step 4B)
# ==============================================================================
# Initialize the Scheduler targeting the fused module
sch = tvm.s_tir.Schedule(mod)

# Retrieve the blocks generated by FuseTIR
block_conv = sch.get_sblock("conv2d_nchw", func_name="fused_conv2d_add_relu")
block_add = sch.get_sblock("T_add", func_name="fused_conv2d_add_relu")
block_relu = sch.get_sblock("compute", func_name="fused_conv2d_add_relu")

# Retrieve the loops of the Conv2d block
# Loops are: batch (nn), out_channel (ff), spatial_y (yy), spatial_x (xx), and reduction loops (rc, ry, rx)
nn, ff, yy, xx, rc, ry, rx = sch.get_loops(block_conv)

# --- Loop Splitting (Tiling) ---
# We slice the spatial dimensions (224x224) into 16x16 tiles.
# 224 / 16 = 14 outer iterations.
y_outer, y_inner = sch.split(yy, factors=[None, 16])
x_outer, x_inner = sch.split(xx, factors=[None, 16])

# --- Loop Reordering ---
# Group the outer loops together, and inner loops together
# This creates a distinct "Tile" level in the loop nest.
sch.reorder(y_outer, x_outer, y_inner, x_inner)

# --- Compute At (Nested Physical Fusion) ---
# We physically move the execution of Add and ReLU *inside* the outer spatial loops of Conv2d.
# This forces the operations to execute completely on a 16x16 tile before moving to the next tile,
# keeping the intermediate data inside the L1 Cache (sblock_alloc_buffer).
sch.reverse_compute_at(block_add, x_outer)
sch.reverse_compute_at(block_relu, x_outer)

print("\n--- 2. After Tiling & Compute At (Cache Optimized) ---")
sch.mod.show()
